php-version = "8.5.0"

[source]
workspace = "."
paths = ["src", "tests", "bench/run.php"]
includes = ["vendor"]
excludes = ["tests/templates"]

[formatter]
print-width = 100
use-tabs = true
array-table-style-alignment = false
empty-line-between-same-symbols = false
preserve-breaking-member-access-chain = true
preserve-breaking-argument-list = true
preserve-breaking-parameter-list = true
preserve-breaking-attribute-list = true
preserve-breaking-conditional-expression = true

[linter]
integrations = []

[linter.rules]
cyclomatic-complexity = {  exclude = ['src/Session.php'] }
kan-defect = {  exclude = ['src/Session.php'] }
literal-named-argument = { enabled = false }
no-literal-password = { exclude = ['tests'] }
readable-literal = { min-digits = 7 }
too-many-methods = { exclude = ['src/Session.php', 'tests'] }
